default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host:     <%= Rails.application.credentials.ride_my_way_database_host %>

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username:ride_my_way
  username: <%= Rails.application.credentials.ride_my_way_database_username %>

  # The password associated with the postgres role (username).
  password: <%= Rails.application.credentials.ride_my_way_database_password %>

development:
  <<: *default
  database: <%= Rails.application.credentials.ride_my_way_database %>

test:
  <<: *default
  database: <%= Rails.application.credentials.ride_my_way_test_database %>

production:
  <<: *default
  database: <%= Rails.application.credentials.ride_my_way_database %>
  username: <%= Rails.application.credentials.ride_my_way_database_username %>
  password: <%= Rails.application.credentials.ride_my_way_database_password %>
